spring:
  application:
    name: 智易搭SEB
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seb
    username: root
    password: root
  data:
    redis:
      host: localhost
      port: 6379
      username: root
      password: 123456
      ttl: 3600

server:
  port: 8123
  servlet:
    context-path: /api

# knife4j
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.yuhao.smarteasybuild.controller
knife4j:
  enable: true
  setting:
    language: zh_cn
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false

# AI
langchain4j:
  open-ai:
    chat-model:
      base-url:
      api-key:
      model-name:
      log-requests:
      log-responses:
      strict-json-schema:

